# Generated by Django 6.0.5 on 2026-05-18 14:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penjaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_uid', models.CharField(max_length=50, unique=True, verbose_name='RFID UID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TongSampah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=100, unique=True, verbose_name='QR/Barcode ID')),
                ('lokasi_atau_tipe', models.CharField(blank=True, help_text='Misal: Tong Sampah Gedung B204', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SesiAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('waktu_mulai', models.DateTimeField(auto_now_add=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('pencatat', 'Pencatat Absensi Siswa'), ('pengawas', 'Membantu/Mengawas Pemilahan')], max_length=20)),
                ('foto_bukti', models.ImageField(blank=True, null=True, upload_to='bukti_absensi/')),
                ('is_submitted', models.BooleanField(default=False)),
                ('penjaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_berjalan', to='penjaga.penjaga')),
            ],
        ),
        migrations.CreateModel(
            name='LogPemilahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_scan', models.DateTimeField(auto_now_add=True)),
                ('sesi_absensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sampah', to='penjaga.sesiabsensi')),
                ('tong_sampah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjaga.tongsampah')),
            ],
            options={
                'unique_together': {('sesi_absensi', 'tong_sampah')},
            },
        ),
    ]
