# Generated by Django 6.0.5 on 2026-05-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjaga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tongsampah',
            name='gambar_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='tongsampah',
            name='lokasi_atau_tipe',
            field=models.CharField(blank=True, help_text='Misal: Tong Organik Gedung A', max_length=100),
        ),
    ]
